# Generated by Django 4.2 on 2023-05-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Articulo',
        ),
    ]
