# Generated by Django 4.2 on 2023-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_rename_producto_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='reference',
            field=models.IntegerField(max_length=10),
        ),
    ]
