# Generated by Django 4.2 on 2023-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0005_remove_categoria_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='reference',
            field=models.IntegerField(max_length=30),
        ),
    ]
