# Generated by Django 4.2 on 2023-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_alter_articulo_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
