# Generated by Django 4.2 on 2023-05-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0007_alter_articulo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
