# Generated by Django 4.2 on 2023-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0008_alter_articulo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='reference',
            field=models.IntegerField(max_length=25),
        ),
    ]
